[LOGGING_CONSTANTS]
LOGGING_NAME = SAGEMCOM
LOGGING_EXCEPTION = 60
LOGGING_TRACE = 5
; time and extras
time_format = {time:YYYY-MM-DD HH:mm:ss.SSS}
extra_modules_format =  {extra[Modules]:<14}
extra_users_format   = | {extra[Users]:<14}
EXTRA_CORRID_FORMAT = CorrID={extra[CorrID]}

; call site
module_format   = | {module:<20}
thread_format   = | {thread.name:<12}
process_format  = | {process.name:<10}
name_format     = | {name:<20}
function_format = | {function:<16}
line_format     = | {line:>4}

; level & message (use Loguru color directive safely)
level_format   = | <level>{level}</level>
message_format = | <level>{message}</level>

[LOGGING_CONFIG]
profile_config_path = logging_config.ini

[DEFAULT_PROFILE]
INITIAL_PROFILE = SDK_NG_CONFIGURATION_PRODUCTION