"""
Shared formatting utilities for WoW-UX MR comments.
Provides Mermaid charts, progress bars, KPI cards, collapsible sections.
"""
from __future__ import annotations

# Universal threshold above which agent-generated content is auto-collapsed.
# Applies both to MR comment <details> blocks and to GitLab CI log sections.
AUTO_COLLAPSE_THRESHOLD = 800


# ── Progress bar ──────────────────────────────────────────────────────────────

def progress_bar(pct: float, width: int = 20) -> str:
    """Return a Unicode block progress bar.  e.g. ``████████░░░░ 67%``"""
    filled = round(pct / 100 * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"`{bar}` **{pct:.1f}%**"


# ── Severity badges ────────────────────────────────────────────────────────────

def sev_badge(level: str) -> str:
    mapping = {
        "HIGH":   "🔴 HIGH",
        "MEDIUM": "🟡 MEDIUM",
        "LOW":    "🟢 LOW",
        "WARN":   "🟠 WARN",
        "INFO":   "🔵 INFO",
        "ERROR":  "🔴 ERROR",
        "WARNING":"🟡 WARNING",
    }
    return mapping.get(level.upper(), level)


def status_badge(ok: bool) -> str:
    return "✅ PASS" if ok else "❌ FAIL"


# ── Mermaid helpers ────────────────────────────────────────────────────────────

def mermaid_pie(title: str, data: dict[str, int]) -> str:
    """Return a fenced Mermaid pie chart block."""
    items = "\n".join(f'    "{k}" : {v}' for k, v in data.items() if v > 0)
    if not items:
        return ""
    return f"```mermaid\npie title {title}\n{items}\n```"


def mermaid_bar(title: str, labels: list[str], values: list[float], y_axis: str = "Value") -> str:
    """Return a fenced Mermaid xychart-beta bar chart block."""
    # GitLab renders xychart-beta; keep label count ≤ 10 for readability
    labels = labels[:10]
    values = values[:10]
    x_str = " ".join(f'"{l}"' for l in labels)
    y_str = " ".join(str(round(v, 1)) for v in values)
    return (
        f"```mermaid\nxychart-beta\n"
        f"    title \"{title}\"\n"
        f"    x-axis [{x_str}]\n"
        f"    y-axis \"{y_axis}\" 0 --> 100\n"
        f"    bar [{y_str}]\n```"
    )


# ── KPI card ──────────────────────────────────────────────────────────────────

def kpi_card(stats: list[tuple[str, str]]) -> str:
    """Return a compact KPI stat row as a markdown table.
    stats: list of (label, value) pairs, e.g. [("Total", "42"), ("HIGH", "🔴 4")]
    """
    header = " | ".join(f"**{label}**" for label, _ in stats)
    values = " | ".join(str(val) for _, val in stats)
    sep = " | ".join(["---"] * len(stats))
    return f"| {header} |\n| {sep} |\n| {values} |"


# ── Collapsible section ───────────────────────────────────────────────────────

def details(summary: str, content: str, open_by_default: bool = False) -> str:
    """Return a collapsible <details> block (closed by default)."""
    attr = " open" if open_by_default else ""
    return f"<details{attr}>\n<summary>{summary}</summary>\n\n{content}\n\n</details>"


def auto_details(summary: str, content: str,
                 threshold: int = AUTO_COLLAPSE_THRESHOLD) -> str:
    """Inline short content, wrap long content in a closed <details>.

    Implements the universal auto-collapse rule: when ``len(content) <= threshold``
    the content is returned verbatim (inline); when it exceeds the threshold it
    is wrapped in a closed ``<details>`` block headed by ``summary``.
    """
    if len(content) <= threshold:
        return content
    return f"<details>\n<summary>{summary}</summary>\n\n{content}\n\n</details>"


def collapsible_table(label: str, header_rows: list[str], data_rows: list[str],
                      visible_count: int = 10) -> str:
    """Hybrid table: top N rows visible + remainder folded into <details>."""
    if not data_rows:
        return ""
    if len(data_rows) <= visible_count:
        return "\n".join(header_rows + data_rows)
    visible = "\n".join(header_rows + data_rows[:visible_count])
    remainder = "\n".join(header_rows + data_rows[visible_count:])
    extra = len(data_rows) - visible_count
    return f"{visible}\n\n{details(f'{label} — show {extra} more row(s)', remainder)}"


# ── Quick wins box ────────────────────────────────────────────────────────────

def quick_wins(items: list[str]) -> str:
    """Render a 'Quick Wins' actionable box (top-3 items)."""
    if not items:
        return ""
    body = "\n".join(f"> - {it}" for it in items[:3])
    return f"> 🎯 **Quick Wins**\n>\n{body}"


# ── Footer signature ──────────────────────────────────────────────────────────

def footer(agent_name: str, pipeline_url: str = "", commit_sha: str = "",
           artifact_url: str = "") -> str:
    """Return a unified footer line for all agent reports."""
    parts = [f"_Generated by **{agent_name}**_"]
    if commit_sha:
        parts.append(f"commit `{commit_sha}`")
    if pipeline_url:
        parts.append(f"[Pipeline]({pipeline_url})")
    if artifact_url:
        parts.append(f"[Artifact]({artifact_url})")
    return f"<sub>{' • '.join(parts)}</sub>"


# ── Agent header banner ───────────────────────────────────────────────────────

def agent_header(emoji: str, title: str, codename: str, mode: str, subtitle: str = "") -> str:
    """Return a standardised agent header block."""
    lines = [
        f"## {emoji} {title} — {codename}",
        "",
        f"<sub>Mode: **{mode}**{' | ' + subtitle if subtitle else ''} | 🕐 `CI Pipeline`</sub>",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


# ── AI Executive Summary block ────────────────────────────────────────────────

_EXEC_BULLET_CAP = 5


def _exec_bullets(items: list[str]) -> str:
    """Render up to 5 bullets, escaping nothing (assumes plain text)."""
    if not items:
        return "_(none)_"
    capped = [str(it).strip().lstrip("-*•").strip() for it in items if str(it).strip()]
    capped = capped[:_EXEC_BULLET_CAP]
    return "\n".join(f"- {it}" for it in capped) if capped else "_(none)_"


def executive_summary(
    summary: str,
    key_points: list[str],
    reviewer_notes: list[str],
    recommended_actions: list[str],
    ai_powered: bool = True,
) -> str:
    """Return the AI Executive Summary collapsible block (open by default).

    Renders a 4-section block: Global Summary, Key Points, Reviewer Notes,
    Recommended Actions. When ``ai_powered=False``, the heading badge changes
    to ``🧮 Deterministic Summary`` and the model footer is omitted.
    """
    badge = "🤖 AI Executive Summary — claude-sonnet-4.6" if ai_powered else "🧮 Deterministic Summary"
    legend = "📋 Summary · 🎯 Key Points · 👁️ Reviewer Notes · ✅ Actions"
    summary_text = (summary or "").strip() or "_(no summary)_"

    body_parts = [
        f"<sub>{legend}</sub>",
        "",
        "### 📋 Global Summary",
        "",
        summary_text,
        "",
        "### 🎯 Key Points",
        "",
        _exec_bullets(key_points),
        "",
        "### 👁️ Reviewer Notes",
        "",
        _exec_bullets(reviewer_notes),
        "",
        "### ✅ Recommended Actions",
        "",
        _exec_bullets(recommended_actions),
    ]
    if ai_powered:
        body_parts.extend(["", "<sub>_powered by claude-sonnet-4.6_</sub>"])

    body = "\n".join(body_parts)
    # Auto-collapse rule: open by default only when body is short enough.
    open_attr = " open" if len(body) <= AUTO_COLLAPSE_THRESHOLD else ""
    return (
        f"<details{open_attr}>\n<summary><strong>{badge}</strong></summary>\n\n"
        f"{body}\n\n"
        "</details>\n"
    )


def render_exec_block(
    ai: dict | None,
    fallback: dict,
) -> str:
    """Render the AI Executive Summary block from an AI dict or fallback dict.

    Both dicts must have keys: ``summary``, ``key_points``, ``reviewer_notes``,
    ``recommended_actions``. ``ai`` may be ``None`` (Copilot unavailable
    or parse failure); the fallback is then used and the badge degrades
    to "🧮 Deterministic Summary".
    """
    chosen = ai if ai else fallback
    return executive_summary(
        summary=str(chosen.get("summary", "")),
        key_points=list(chosen.get("key_points") or []),
        reviewer_notes=list(chosen.get("reviewer_notes") or []),
        recommended_actions=list(chosen.get("recommended_actions") or []),
        ai_powered=ai is not None,
    )
